/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ContactId = bigint;
export interface ContactMessage {
  'id' : ContactId,
  'name' : string,
  'createdAt' : Timestamp,
  'email' : string,
  'message' : string,
}
export interface CreateContactArgs {
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface CreateNoticeArgs {
  'title' : string,
  'content' : string,
  'category' : NoticeCategory,
}
export interface CreateStudentArgs {
  'class' : string,
  'name' : string,
  'nameBengali' : string,
  'section' : string,
  'email' : string,
  'rollNumber' : string,
}
export interface CreateTeacherArgs {
  'subject' : string,
  'name' : string,
  'nameBengali' : string,
  'email' : string,
  'phone' : string,
  'qualification' : string,
  'subjectBengali' : string,
}
export interface Notice {
  'id' : NoticeId,
  'title' : string,
  'content' : string,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'pinned' : boolean,
  'category' : NoticeCategory,
  'authorPrincipal' : Principal,
}
export type NoticeCategory = { 'Academic' : null } |
  { 'General' : null } |
  { 'Holiday' : null } |
  { 'Alert' : null } |
  { 'Other' : null };
export type NoticeId = bigint;
export interface Student {
  'id' : StudentId,
  'class' : string,
  'name' : string,
  'nameBengali' : string,
  'section' : string,
  'email' : string,
  'rollNumber' : string,
}
export type StudentId = bigint;
export interface Teacher {
  'id' : TeacherId,
  'subject' : string,
  'name' : string,
  'nameBengali' : string,
  'email' : string,
  'phone' : string,
  'qualification' : string,
  'subjectBengali' : string,
}
export type TeacherId = bigint;
export type Timestamp = bigint;
export interface UpdateNoticeArgs {
  'id' : NoticeId,
  'title' : string,
  'content' : string,
  'category' : NoticeCategory,
}
export interface UpdateStudentArgs {
  'id' : StudentId,
  'class' : string,
  'name' : string,
  'nameBengali' : string,
  'section' : string,
  'email' : string,
  'rollNumber' : string,
}
export interface UpdateTeacherArgs {
  'id' : TeacherId,
  'subject' : string,
  'name' : string,
  'nameBengali' : string,
  'email' : string,
  'phone' : string,
  'qualification' : string,
  'subjectBengali' : string,
}
export interface _SERVICE {
  'createNotice' : ActorMethod<[CreateNoticeArgs], Notice>,
  'createStudent' : ActorMethod<[CreateStudentArgs], Student>,
  'createTeacher' : ActorMethod<[CreateTeacherArgs], Teacher>,
  'deleteNotice' : ActorMethod<[NoticeId], boolean>,
  'deleteStudent' : ActorMethod<[StudentId], boolean>,
  'deleteTeacher' : ActorMethod<[TeacherId], boolean>,
  'getAllStudents' : ActorMethod<[], Array<Student>>,
  'getAllTeachers' : ActorMethod<[], Array<Teacher>>,
  'getContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getNoticeById' : ActorMethod<[NoticeId], [] | [Notice]>,
  'getNotices' : ActorMethod<[], Array<Notice>>,
  'getStudents' : ActorMethod<[], Array<Student>>,
  'getTeachers' : ActorMethod<[], Array<Teacher>>,
  'isAdmin' : ActorMethod<[], boolean>,
  'pinNotice' : ActorMethod<[NoticeId, boolean], boolean>,
  'setAdmin' : ActorMethod<[Principal], boolean>,
  'submitContactMessage' : ActorMethod<[CreateContactArgs], ContactMessage>,
  'updateNotice' : ActorMethod<[UpdateNoticeArgs], boolean>,
  'updateStudent' : ActorMethod<[UpdateStudentArgs], boolean>,
  'updateTeacher' : ActorMethod<[UpdateTeacherArgs], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];