/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const NoticeCategory = IDL.Variant({
  'Academic' : IDL.Null,
  'General' : IDL.Null,
  'Holiday' : IDL.Null,
  'Alert' : IDL.Null,
  'Other' : IDL.Null,
});
export const CreateNoticeArgs = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'category' : NoticeCategory,
});
export const NoticeId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Notice = IDL.Record({
  'id' : NoticeId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'pinned' : IDL.Bool,
  'category' : NoticeCategory,
  'authorPrincipal' : IDL.Principal,
});
export const CreateStudentArgs = IDL.Record({
  'class' : IDL.Text,
  'name' : IDL.Text,
  'nameBengali' : IDL.Text,
  'section' : IDL.Text,
  'email' : IDL.Text,
  'rollNumber' : IDL.Text,
});
export const StudentId = IDL.Nat;
export const Student = IDL.Record({
  'id' : StudentId,
  'class' : IDL.Text,
  'name' : IDL.Text,
  'nameBengali' : IDL.Text,
  'section' : IDL.Text,
  'email' : IDL.Text,
  'rollNumber' : IDL.Text,
});
export const CreateTeacherArgs = IDL.Record({
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'nameBengali' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'qualification' : IDL.Text,
  'subjectBengali' : IDL.Text,
});
export const TeacherId = IDL.Nat;
export const Teacher = IDL.Record({
  'id' : TeacherId,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'nameBengali' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'qualification' : IDL.Text,
  'subjectBengali' : IDL.Text,
});
export const ContactId = IDL.Nat;
export const ContactMessage = IDL.Record({
  'id' : ContactId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const CreateContactArgs = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const UpdateNoticeArgs = IDL.Record({
  'id' : NoticeId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'category' : NoticeCategory,
});
export const UpdateStudentArgs = IDL.Record({
  'id' : StudentId,
  'class' : IDL.Text,
  'name' : IDL.Text,
  'nameBengali' : IDL.Text,
  'section' : IDL.Text,
  'email' : IDL.Text,
  'rollNumber' : IDL.Text,
});
export const UpdateTeacherArgs = IDL.Record({
  'id' : TeacherId,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'nameBengali' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'qualification' : IDL.Text,
  'subjectBengali' : IDL.Text,
});

export const idlService = IDL.Service({
  'createNotice' : IDL.Func([CreateNoticeArgs], [Notice], []),
  'createStudent' : IDL.Func([CreateStudentArgs], [Student], []),
  'createTeacher' : IDL.Func([CreateTeacherArgs], [Teacher], []),
  'deleteNotice' : IDL.Func([NoticeId], [IDL.Bool], []),
  'deleteStudent' : IDL.Func([StudentId], [IDL.Bool], []),
  'deleteTeacher' : IDL.Func([TeacherId], [IDL.Bool], []),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], []),
  'getAllTeachers' : IDL.Func([], [IDL.Vec(Teacher)], []),
  'getContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], []),
  'getNoticeById' : IDL.Func([NoticeId], [IDL.Opt(Notice)], ['query']),
  'getNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
  'getStudents' : IDL.Func([], [IDL.Vec(Student)], []),
  'getTeachers' : IDL.Func([], [IDL.Vec(Teacher)], []),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'pinNotice' : IDL.Func([NoticeId, IDL.Bool], [IDL.Bool], []),
  'setAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'submitContactMessage' : IDL.Func([CreateContactArgs], [ContactMessage], []),
  'updateNotice' : IDL.Func([UpdateNoticeArgs], [IDL.Bool], []),
  'updateStudent' : IDL.Func([UpdateStudentArgs], [IDL.Bool], []),
  'updateTeacher' : IDL.Func([UpdateTeacherArgs], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const NoticeCategory = IDL.Variant({
    'Academic' : IDL.Null,
    'General' : IDL.Null,
    'Holiday' : IDL.Null,
    'Alert' : IDL.Null,
    'Other' : IDL.Null,
  });
  const CreateNoticeArgs = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'category' : NoticeCategory,
  });
  const NoticeId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Notice = IDL.Record({
    'id' : NoticeId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'pinned' : IDL.Bool,
    'category' : NoticeCategory,
    'authorPrincipal' : IDL.Principal,
  });
  const CreateStudentArgs = IDL.Record({
    'class' : IDL.Text,
    'name' : IDL.Text,
    'nameBengali' : IDL.Text,
    'section' : IDL.Text,
    'email' : IDL.Text,
    'rollNumber' : IDL.Text,
  });
  const StudentId = IDL.Nat;
  const Student = IDL.Record({
    'id' : StudentId,
    'class' : IDL.Text,
    'name' : IDL.Text,
    'nameBengali' : IDL.Text,
    'section' : IDL.Text,
    'email' : IDL.Text,
    'rollNumber' : IDL.Text,
  });
  const CreateTeacherArgs = IDL.Record({
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'nameBengali' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'qualification' : IDL.Text,
    'subjectBengali' : IDL.Text,
  });
  const TeacherId = IDL.Nat;
  const Teacher = IDL.Record({
    'id' : TeacherId,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'nameBengali' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'qualification' : IDL.Text,
    'subjectBengali' : IDL.Text,
  });
  const ContactId = IDL.Nat;
  const ContactMessage = IDL.Record({
    'id' : ContactId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const CreateContactArgs = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const UpdateNoticeArgs = IDL.Record({
    'id' : NoticeId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'category' : NoticeCategory,
  });
  const UpdateStudentArgs = IDL.Record({
    'id' : StudentId,
    'class' : IDL.Text,
    'name' : IDL.Text,
    'nameBengali' : IDL.Text,
    'section' : IDL.Text,
    'email' : IDL.Text,
    'rollNumber' : IDL.Text,
  });
  const UpdateTeacherArgs = IDL.Record({
    'id' : TeacherId,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'nameBengali' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'qualification' : IDL.Text,
    'subjectBengali' : IDL.Text,
  });
  
  return IDL.Service({
    'createNotice' : IDL.Func([CreateNoticeArgs], [Notice], []),
    'createStudent' : IDL.Func([CreateStudentArgs], [Student], []),
    'createTeacher' : IDL.Func([CreateTeacherArgs], [Teacher], []),
    'deleteNotice' : IDL.Func([NoticeId], [IDL.Bool], []),
    'deleteStudent' : IDL.Func([StudentId], [IDL.Bool], []),
    'deleteTeacher' : IDL.Func([TeacherId], [IDL.Bool], []),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], []),
    'getAllTeachers' : IDL.Func([], [IDL.Vec(Teacher)], []),
    'getContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], []),
    'getNoticeById' : IDL.Func([NoticeId], [IDL.Opt(Notice)], ['query']),
    'getNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
    'getStudents' : IDL.Func([], [IDL.Vec(Student)], []),
    'getTeachers' : IDL.Func([], [IDL.Vec(Teacher)], []),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'pinNotice' : IDL.Func([NoticeId, IDL.Bool], [IDL.Bool], []),
    'setAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'submitContactMessage' : IDL.Func(
        [CreateContactArgs],
        [ContactMessage],
        [],
      ),
    'updateNotice' : IDL.Func([UpdateNoticeArgs], [IDL.Bool], []),
    'updateStudent' : IDL.Func([UpdateStudentArgs], [IDL.Bool], []),
    'updateTeacher' : IDL.Func([UpdateTeacherArgs], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };