/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CreateContactArgs {
    name: string;
    email: string;
    message: string;
}
export interface CreateTeacherArgs {
    subject: string;
    name: string;
    nameBengali: string;
    email: string;
    phone: string;
    qualification: string;
    subjectBengali: string;
}
export type Timestamp = bigint;
export type ContactId = bigint;
export interface Teacher {
    id: TeacherId;
    subject: string;
    name: string;
    nameBengali: string;
    email: string;
    phone: string;
    qualification: string;
    subjectBengali: string;
}
export interface UpdateTeacherArgs {
    id: TeacherId;
    subject: string;
    name: string;
    nameBengali: string;
    email: string;
    phone: string;
    qualification: string;
    subjectBengali: string;
}
export type TeacherId = bigint;
export type StudentId = bigint;
export interface ContactMessage {
    id: ContactId;
    name: string;
    createdAt: Timestamp;
    email: string;
    message: string;
}
export interface Notice {
    id: NoticeId;
    title: string;
    content: string;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    pinned: boolean;
    category: NoticeCategory;
    authorPrincipal: Principal;
}
export interface UpdateNoticeArgs {
    id: NoticeId;
    title: string;
    content: string;
    category: NoticeCategory;
}
export interface CreateNoticeArgs {
    title: string;
    content: string;
    category: NoticeCategory;
}
export interface UpdateStudentArgs {
    id: StudentId;
    class: string;
    name: string;
    nameBengali: string;
    section: string;
    email: string;
    rollNumber: string;
}
export type NoticeId = bigint;
export interface CreateStudentArgs {
    class: string;
    name: string;
    nameBengali: string;
    section: string;
    email: string;
    rollNumber: string;
}
export interface Student {
    id: StudentId;
    class: string;
    name: string;
    nameBengali: string;
    section: string;
    email: string;
    rollNumber: string;
}
export enum NoticeCategory {
    Academic = "Academic",
    General = "General",
    Holiday = "Holiday",
    Alert = "Alert",
    Other = "Other"
}
export interface backendInterface {
    createNotice(args: CreateNoticeArgs): Promise<Notice>;
    createStudent(args: CreateStudentArgs): Promise<Student>;
    createTeacher(args: CreateTeacherArgs): Promise<Teacher>;
    deleteNotice(id: NoticeId): Promise<boolean>;
    deleteStudent(id: StudentId): Promise<boolean>;
    deleteTeacher(id: TeacherId): Promise<boolean>;
    getAllStudents(): Promise<Array<Student>>;
    getAllTeachers(): Promise<Array<Teacher>>;
    getContactMessages(): Promise<Array<ContactMessage>>;
    getNoticeById(id: NoticeId): Promise<Notice | null>;
    getNotices(): Promise<Array<Notice>>;
    getStudents(): Promise<Array<Student>>;
    getTeachers(): Promise<Array<Teacher>>;
    isAdmin(): Promise<boolean>;
    pinNotice(id: NoticeId, pinned: boolean): Promise<boolean>;
    setAdmin(newAdmin: Principal): Promise<boolean>;
    submitContactMessage(args: CreateContactArgs): Promise<ContactMessage>;
    updateNotice(args: UpdateNoticeArgs): Promise<boolean>;
    updateStudent(args: UpdateStudentArgs): Promise<boolean>;
    updateTeacher(args: UpdateTeacherArgs): Promise<boolean>;
}
import type { CreateNoticeArgs as _CreateNoticeArgs, Notice as _Notice, NoticeCategory as _NoticeCategory, NoticeId as _NoticeId, Timestamp as _Timestamp, UpdateNoticeArgs as _UpdateNoticeArgs } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createNotice(arg0: CreateNoticeArgs): Promise<Notice> {
        if (this.processError) {
            try {
                const result = await this.actor.createNotice(to_candid_CreateNoticeArgs_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Notice_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNotice(to_candid_CreateNoticeArgs_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Notice_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createStudent(arg0: CreateStudentArgs): Promise<Student> {
        if (this.processError) {
            try {
                const result = await this.actor.createStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStudent(arg0);
            return result;
        }
    }
    async createTeacher(arg0: CreateTeacherArgs): Promise<Teacher> {
        if (this.processError) {
            try {
                const result = await this.actor.createTeacher(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTeacher(arg0);
            return result;
        }
    }
    async deleteNotice(arg0: NoticeId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNotice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNotice(arg0);
            return result;
        }
    }
    async deleteStudent(arg0: StudentId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudent(arg0);
            return result;
        }
    }
    async deleteTeacher(arg0: TeacherId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTeacher(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTeacher(arg0);
            return result;
        }
    }
    async getAllStudents(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudents();
            return result;
        }
    }
    async getAllTeachers(): Promise<Array<Teacher>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTeachers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTeachers();
            return result;
        }
    }
    async getContactMessages(): Promise<Array<ContactMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactMessages();
            return result;
        }
    }
    async getNoticeById(arg0: NoticeId): Promise<Notice | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNoticeById(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNoticeById(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotices(): Promise<Array<Notice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotices();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotices();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudents(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudents();
            return result;
        }
    }
    async getTeachers(): Promise<Array<Teacher>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeachers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeachers();
            return result;
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async pinNotice(arg0: NoticeId, arg1: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.pinNotice(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pinNotice(arg0, arg1);
            return result;
        }
    }
    async setAdmin(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdmin(arg0);
            return result;
        }
    }
    async submitContactMessage(arg0: CreateContactArgs): Promise<ContactMessage> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactMessage(arg0);
            return result;
        }
    }
    async updateNotice(arg0: UpdateNoticeArgs): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNotice(to_candid_UpdateNoticeArgs_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNotice(to_candid_UpdateNoticeArgs_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateStudent(arg0: UpdateStudentArgs): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudent(arg0);
            return result;
        }
    }
    async updateTeacher(arg0: UpdateTeacherArgs): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTeacher(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTeacher(arg0);
            return result;
        }
    }
}
function from_candid_NoticeCategory_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NoticeCategory): NoticeCategory {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Notice_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notice): Notice {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Notice]): Notice | null {
    return value.length === 0 ? null : from_candid_Notice_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _NoticeId;
    title: string;
    content: string;
    createdAt: _Timestamp;
    updatedAt: _Timestamp;
    pinned: boolean;
    category: _NoticeCategory;
    authorPrincipal: Principal;
}): {
    id: NoticeId;
    title: string;
    content: string;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    pinned: boolean;
    category: NoticeCategory;
    authorPrincipal: Principal;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        pinned: value.pinned,
        category: from_candid_NoticeCategory_n7(_uploadFile, _downloadFile, value.category),
        authorPrincipal: value.authorPrincipal
    };
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Academic: null;
} | {
    General: null;
} | {
    Holiday: null;
} | {
    Alert: null;
} | {
    Other: null;
}): NoticeCategory {
    return "Academic" in value ? NoticeCategory.Academic : "General" in value ? NoticeCategory.General : "Holiday" in value ? NoticeCategory.Holiday : "Alert" in value ? NoticeCategory.Alert : "Other" in value ? NoticeCategory.Other : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notice>): Array<Notice> {
    return value.map((x)=>from_candid_Notice_n5(_uploadFile, _downloadFile, x));
}
function to_candid_CreateNoticeArgs_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateNoticeArgs): _CreateNoticeArgs {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_NoticeCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NoticeCategory): _NoticeCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateNoticeArgs_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateNoticeArgs): _UpdateNoticeArgs {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: NoticeId;
    title: string;
    content: string;
    category: NoticeCategory;
}): {
    id: _NoticeId;
    title: string;
    content: string;
    category: _NoticeCategory;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        category: to_candid_NoticeCategory_n3(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    content: string;
    category: NoticeCategory;
}): {
    title: string;
    content: string;
    category: _NoticeCategory;
} {
    return {
        title: value.title,
        content: value.content,
        category: to_candid_NoticeCategory_n3(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NoticeCategory): {
    Academic: null;
} | {
    General: null;
} | {
    Holiday: null;
} | {
    Alert: null;
} | {
    Other: null;
} {
    return value == NoticeCategory.Academic ? {
        Academic: null
    } : value == NoticeCategory.General ? {
        General: null
    } : value == NoticeCategory.Holiday ? {
        Holiday: null
    } : value == NoticeCategory.Alert ? {
        Alert: null
    } : value == NoticeCategory.Other ? {
        Other: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
